### // Buscar todos los productos
GET http://localhost:3001/product


### // Buscar producto por nombre
GET http://localhost:3001/product?name=OPPOF


### // Buscar todos los servicios
GET http://localhost:3001/service


### // Buscar servicio por nombre
GET http://localhost:3001/service?name=B


### // Crear servicio 
POST http://localhost:3001/service HTTP/1.1
Content-Type: application/json

{
    "name": "B",
    "description": "Costura fina",
    "price": 250.23,
    "userId": 1
}


### // Borrar servicio por ID
DELETE http://localhost:3001/service/1



### // Payment
POST  http://localhost:3001/payment HTTP/1.1
Content-Type: application/json

{
    "items":[
        {
            "name":"Pelota",
            "unit_price":240,
            "quantity":1
        }
    ],
    "payer": {
        "name": "Juan",
        "surname": "Lopez",
        "email": "user@email.com",
        "phone": {
            "area_code": "11",
            "number": "4444-4444"
        },
        "identification": {
            "type": "DNI",
            "number": "12345678"
        },
        "address": {
            "street_name": "Street",
            "street_number": 123,
            "zip_code": "5700"
        }
    }
}
